version: '3.4'

x-base-services:
  golang: &base-go
    build:
      context: .
    volumes:
      - .:/app

services:
  envoy:
    image: envoyproxy/envoy
    volumes:
      - .:/etc/envoy
    ports:
      - 10000
      - 10001
  discovery:
    <<: *base-go
    command: go run ./discovery
  extauth:
    <<: *base-go
    command: go run ./extauth